### ISSUE TITLE
Some files not deleted after uninstall

### ISSUE THREAD

**Issue by frossigneux** [Scille/parsec-build#17]
At startup, some old files cause a crash:
```
C:\Program Files (x86)\Parsec\core>parsec.exe
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python36-x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "parsec/cli.py", line 6, in <module>
  File "C:\projects\parsec-build\parsec-cloud\parsec\cli_utils.py", line 3, in <module>
  File "C:\Python36-x64\lib\site-packages\trio\__init__.py", line 18, in <module>
  File "C:\Python36-x64\lib\site-packages\trio\_core\__init__.py", line 24, in <module>
  File "C:\Python36-x64\lib\site-packages\trio\_core\_ki.py", line 9, in <module>
  File "C:\Python36-x64\lib\site-packages\trio\_util.py", line 67, in <module>
  File "C:\Python36-x64\lib\site-packages\cffi\api.py", line 56, in __init__
Exception: Version mismatch: this is the 'cffi' package version 1.12.2, located in 'C:\\Program Files (x86)\\Parsec\\core\\lib\\cffi\\api.pyc'.  When we import the top-level '_cffi_backend' extension module, we get version 1.12.1, located in 'C:\\Program Files (x86)\\Parsec\\core\\lib\\_cffi_backend.cp36-win_amd64.pyd'.  The two versions should be equal; check your installation.
```

**Comment by frossigneux** [comment]
Caused by already running instance...
See https://github.com/Scille/parsec-build/pull/23
